module.exports = {
  "extends": ["./browser.js", "plugin:react/recommended"],
  "rules": {
    "react/forbid-component-props": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-closing-bracket-location": "error",
    "react/jsx-curly-spacing": ["error", "always"],
    "react/jsx-equals-spacing": "error",
    "react/jsx-filename-extension": "error",
    "react/jsx-first-prop-new-line": ["error", "multiline"],
    "react/jsx-handler-names": "error",
    "react/jsx-indent-props": "error",
    "react/jsx-indent": "error",
    "react/jsx-max-props-per-line": "error",
    "react/jsx-no-bind": ["error", {
        "ignoreRefs": true,
    }],
    "react/jsx-no-literals": "error",
    "react/jsx-pascal-case": "error",
    "react/jsx-tag-spacing": "error",
    "react/jsx-wrap-multilines": "error",
    "react/no-danger": "error",
    "react/no-did-mount-set-state": "error",
    "react/no-did-update-set-state": "error",
    "react/no-multi-comp": "error",
    "react/no-unused-prop-types": "error",
    "react/no-will-update-set-state": ["error", "disallow-in-func"],
    "react/prefer-es6-class": "error",
    "react/require-optimization": "error",
    "react/self-closing-comp": "error",
    "react/sort-comp": "error",
    "react/sort-prop-types": "error",
    "react/style-prop-object": "error",
  },
};
