module.exports = {
    extends: ['eslint:recommended', './babel'],
    env: {
        es2022: true,
    },
    rules: {
        'accessor-pairs': 'error',
        'arrow-body-style': 'error',
        'camelcase': [
            'error',
            {
                ignoreDestructuring: true,
                ignoreGlobals: true,
                ignoreImports: true,
            },
        ],
        'capitalized-comments': 'error',
        'complexity': 'error',
        'consistent-return': 'error',
        'consistent-this': ['error', 'self'],
        'default-case-last': 'error',
        'default-param-last': 'error',
        'dot-notation': 'error',
        'eqeqeq': 'error',
        'func-name-matching': 'error',
        'func-names': 'error',
        'func-style': 'error',
        'grouped-accessor-pairs': ['error', 'getBeforeSet'],
        'guard-for-in': 'error',
        'line-comment-position': 'error',
        'lines-around-comment': [
            'error',
            {
                afterBlockComment: false,
                afterLineComment: false,
                allowBlockStart: false,
                allowBlockEnd: false,
            },
        ],
        'lines-between-class-members': [
            'error',
            'always',
            {
                exceptAfterSingleLine: true,
            },
        ],
        'logical-assignment-operators': [
            'error',
            'always',
            { enforceForIfStatements: true },
        ],
        'max-classes-per-file': 'error',
        'max-depth': 'error',
        'max-nested-callbacks': [
            'error',
            {
                max: 4,
            },
        ],
        'max-params': 'error',
        'max-statements-per-line': 'error',
        'multiline-comment-style': 'error',
        'new-cap': 'error',
        'no-array-constructor': 'error',
        'no-await-in-loop': 'error',
        'no-caller': 'error',
        'no-confusing-arrow': [
            'error',
            {
                allowParens: false,
            },
        ],
        'no-constant-binary-expression': 'error',
        'no-constructor-return': 'error',
        'no-div-regex': 'error',
        'no-duplicate-imports': 'error',
        'no-else-return': 'error',
        'no-empty-function': 'error',
        'no-empty-static-block': 'error',
        'no-eq-null': 'error',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-label': 'error',
        'no-implicit-coercion': 'error',
        'no-implied-eval': 'error',
        'no-inline-comments': 'error',
        'no-iterator': 'error',
        'no-label-var': 'error',
        'no-labels': [
            'error',
            {
                allowLoop: true,
            },
        ],
        'no-lone-blocks': 'error',
        'no-lonely-if': 'error',
        'no-loop-func': 'error',
        'no-multi-assign': 'error',
        'no-multi-str': 'error',
        'no-nested-ternary': 'error',
        'no-new-func': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-new-object': 'error',
        'no-new-wrappers': 'error',
        'no-octal-escape': 'error',
        'no-promise-executor-return': 'error',
        'no-proto': 'error',
        'no-return-assign': 'error',
        'no-return-await': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-shadow': 'error',
        'no-template-curly-in-string': 'error',
        'no-throw-literal': 'error',
        'no-undef-init': 'error',
        'no-undef': 'error',
        'no-undefined': 'error',
        'no-underscore-dangle': [
            'error',
            {
                enforceInClassFields: true,
                enforceInMethodNames: true,
            },
        ],
        'no-unmodified-loop-condition': 'error',
        'no-unneeded-ternary': 'error',
        'no-unreachable-loop': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': [
            'error',
            {
                disallowArithmeticOperators: true,
            },
        ],
        'no-unused-private-class-members': 'error',
        'no-unused-vars': [
            'error',
            {
                varsIgnorePattern: '_',
            },
        ],
        'no-use-before-define': 'error',
        'no-useless-call': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-concat': 'error',
        'no-useless-constructor': 'error',
        'no-useless-rename': 'error',
        'no-useless-return': 'error',
        'no-var': 'error',
        'no-void': 'error',
        'no-warning-comments': 'error',
        'object-shorthand': ['error', 'properties'],
        'padding-line-between-statements': [
            'error',
            // Require a blank line before returns
            {
                blankLine: 'always',
                prev: '*',
                next: 'return',
            },

            // Require a blank line after a sequence of variable declarations
            {
                blankLine: 'always',
                prev: ['const', 'let', 'var'],
                next: '*',
            },
            {
                blankLine: 'any',
                prev: ['const', 'let', 'var'],
                next: ['const', 'let', 'var'],
            },

            // Require a blank line after blocks
            {
                blankLine: 'always',
                prev: 'block',
                next: '*',
            },

            // Require a blank line before exports
            {
                blankLine: 'always',
                prev: ['cjs-export', 'export'],
                next: '*',
            },
            {
                blankLine: 'any',
                prev: ['cjs-export', 'export'],
                next: ['cjs-export', 'export'],
            },

            // Require a blank line after a sequence of imports/requires
            {
                blankLine: 'always',
                prev: ['cjs-import', 'import'],
                next: '*',
            },
            {
                blankLine: 'any',
                prev: ['cjs-import', 'import'],
                next: ['cjs-import', 'import'],
            },
        ],
        'prefer-arrow-callback': [
            'error',
            {
                allowNamedFunctions: true,
            },
        ],
        'prefer-const': 'error',
        'prefer-destructuring': [
            'error',
            {
                array: false,
                object: true,
            },
        ],
        'prefer-exponentiation-operator': 'error',
        'prefer-object-has-own': 'error',
        'prefer-object-spread': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-reflect': 'error',
        'prefer-regex-literals': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'error',
        'radix': ['error', 'as-needed'],
        'require-atomic-updates': 'error',
        'require-await': 'error',
        'require-unicode-regexp': 'error',
        'sort-keys': [
            'error',
            'asc',
            {
                caseSensitive: false,
                natural: true,
            },
        ],
        'spaced-comment': [
            'error',
            'always',
            {
                block: {
                    balanced: true,
                    exceptions: ['*'],
                    markers: ['!'],
                },
            },
        ],
        'yoda': 'error',
    },
};
